#!/usr/bin/env python3
"""
refresh-chatgpt-tokens.py — pull current chatgpt.com session tokens from Brave
and write them to ~/.config/tokenmaxx/chatgpt.env.

Cron sources that env file before running quota-codex.js, so this script is
the single point of truth for token freshness. Run weekly (or on demand) to
keep quota polling working.

Requires:
  - pycookiecheat (pip install pycookiecheat)
  - Brave Browser logged in to chatgpt.com under Profile 1

Usage:
  python3 refresh-chatgpt-tokens.py
  python3 refresh-chatgpt-tokens.py --profile "Profile 2"
  python3 refresh-chatgpt-tokens.py --out /custom/path/chatgpt.env
"""

import argparse
import os
import sys
from datetime import datetime
from pathlib import Path

try:
    from pycookiecheat import chrome_cookies
except ImportError:
    print("ERROR: pycookiecheat not installed. Run: pip3 install pycookiecheat", file=sys.stderr)
    sys.exit(1)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--profile",
        default="Profile 1",
        help='Brave profile directory name (default: "Profile 1")',
    )
    parser.add_argument(
        "--out",
        default=os.path.expanduser("~/.config/tokenmaxx/chatgpt.env"),
        help="Output env file path",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be written; don't write file",
    )
    args = parser.parse_args()

    cookie_file = os.path.expanduser(
        f"~/Library/Application Support/BraveSoftware/Brave-Browser/{args.profile}/Cookies"
    )
    if not os.path.exists(cookie_file):
        print(f"ERROR: Brave cookie file not found: {cookie_file}", file=sys.stderr)
        return 1

    try:
        cookies = chrome_cookies(
            "https://chatgpt.com",
            browser="Brave",
            cookie_file=cookie_file,
        )
    except Exception as e:
        print(f"ERROR: failed to read cookies: {e}", file=sys.stderr)
        return 1

    t0 = cookies.get("__Secure-next-auth.session-token.0", "")
    t1 = cookies.get("__Secure-next-auth.session-token.1", "")

    if not t0 or not t1:
        print(
            "ERROR: session-token.0 or .1 missing — are you logged in to chatgpt.com in Brave?",
            file=sys.stderr,
        )
        return 1

    now = datetime.utcnow().isoformat() + "Z"
    contents = (
        f"# Auto-generated by refresh-chatgpt-tokens.py at {now}\n"
        f"# Source this file from cron: set -a; . ~/.config/tokenmaxx/chatgpt.env; set +a\n"
        f"CHATGPT_SESSION_TOKEN_0={t0}\n"
        f"CHATGPT_SESSION_TOKEN_1={t1}\n"
    )

    if args.dry_run:
        print(f"[dry-run] would write {len(contents)} bytes to {args.out}")
        print(f"  TOKEN_0 length: {len(t0)}")
        print(f"  TOKEN_1 length: {len(t1)}")
        return 0

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(contents)
    out_path.chmod(0o600)
    print(f"OK: wrote tokens to {args.out} ({len(t0)} + {len(t1)} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
